
services:
  qlish-backend:
    image: qlish-api:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MONGO_URI: ${mongodb_url}
    volumes:
      - ./src:/app/src  # Bind-mount source code for live-reload
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-dev:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"


volumes:
  mongo-data-dev:
  redis-data-dev:
