spring:
  application:
    name: qlish-api
  data:
    mongodb:
      uri: ${mongodb_url}
      database: ${db_name}
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: Kolade Amire

server:
  port: 8081
  error:
    include-message: always

logging:
  level:
    org:
      springframework: DEBUG
      springframework.security: TRACE



