spring:
  application:
    name: qlish-api
  docker:
    compose:
      enabled: false
  session:
    redis:
      flush-mode: on-save
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: ${GOOGLE_CLIENT_REDIRECT_URI}
        provider:
          google:
            authorization-uri: ${GOOGLE_CLIENT_AUTHORIZATION_URI}
            token-uri: ${GOOGLE_CLIENT_TOKEN_URI}
            user-info-uri: ${USER_INFO_URI}
            user-name-attribute: sub
  data:
    mongodb:
      uri: ${MONGO_URL}
      database: ${DB_NAME}
      password: ${MONGO_PASSWORD}
      username: ${MONGO_USERNAME}
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    org:
      springframework: DEBUG
      springframework.security: TRACE
      liquibase: DEBUG
