spring:
  application:
    name: qlish-api
  docker:
    compose:
      enabled: false
  session:
    redis:
      flush-mode: on-save

  data:
    mongodb:
      uri: ${MONGO_URL}
      database: ${DB_NAME}
      password: ${MONGO_PASSWORD}
      username: ${MONGO_USERNAME}
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: none
  error:
    include-message: always

logging:
  level:
    org:
      springframework: DEBUG
      springframework.security: TRACE
      liquibase: DEBUG
