spring:
  application:
    name: qlish-api
  data:
    mongodb:
      uri: ${mongodb_url}
      database: ${db_name}

server:
  port: 8081
  error:
    include-message: always

logging:
  level:
    org:
      springframework: DEBUG
      springframework.security: TRACE


