spring:
  application:
    name: qlish-api
  docker:
    compose:
      enabled: false
  data:
    mongodb:
      uri: ${mongodb_url}
      database: ${db_name}
      password: ${mongodb_password}
      username: ${mongodb_username}
    redis:
      host: ${REDIS_HOST}
      port: 6379
      timeout: 6000

server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    org:
      springframework: DEBUG
      springframework.security: TRACE
      liquibase: DEBUG
